apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep1
  labels:
    app: dm
spec:
  replicas: 7
  selector:
    matchLabels:
      app: dm
  template:
    metadata:
      labels:
        app: dm
    spec:
      containers:
        - name: cont1
          image: shammu101/game
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc1
spec:
  type: NodePort
  selector:
    app: dm
  ports:
    - port: 80
      targetPort: 80
